### ISSUE TITLE
'ascii' codec can't encode character u'\u2019' in position 56: ordinal not in range(128)

### ISSUE THREAD

**Issue by UnityEQ** [minimaxir/facebook-ad-library-scraper#2]
Any advice on this one? It's default installation.

python fb_ad_lib_scraper.py
  1%|1         | 1/100 [00:01<02:05,  1.27s/it]Traceback (most recent call last):
  File "fb_ad_lib_scraper.py", line 98, in <module>
    w1.writerow(ad)
  File "C:\Python27\lib\csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 56: ordinal not in range(128)
  1%|1         | 1/100 [00:01<02:07,  1.29s/it]

**Comment by UnityEQ** [comment]
i was thinking something like this:
w1.writerow([unicode(ads).encode("utf-8") for ads in ad])

But then I get this:

python fb_ad_lib_scraper.py
  0%|          | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "fb_ad_lib_scraper.py", line 99, in <module>
    w1.writerow([unicode(ads).encode("utf-8") for ads in ad])
  File "C:\Python27\lib\csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Python27\lib\csv.py", line 149, in _dict_to_list
    return [rowdict.get(key, self.restval) for key in self.fieldnames]
AttributeError: 'list' object has no attribute 'get'
  0%|          | 0/100 [00:01<?, ?it/s]

**Comment by minimaxir** [comment]
This script is only designed to work for Python 3; you _really_ shouldn't be using Python 2 nowadays.

Support for Python 2 will not be added.
